# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AsBuiltMeNow
                                 A QGIS plugin
 Update design features according to specified constructed features list
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-11
        copyright            : (C) 2024 by Ian McHugh
        email                : imchugh00@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AsBuiltMeNow class from file AsBuiltMeNow.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AsBuiltMeNow import AsBuiltMeNow
    return AsBuiltMeNow(iface)
